[dominion-react]
image=localhost/opensuse-tumbleweed-template
hostname=dominion-react
start_now=true
# Make distrobox can open browser link
init_hooks=sudo ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open;
# Install Google Antigravity
init_hooks=sudo zypper ar -f -G https://us-central1-yum.pkg.dev/projects/antigravity-auto-updater-dev/antigravity-rpm antigravity-rpm;
init_hooks=sudo zypper ref;
init_hooks=sudo zypper in -y antigravity;

